# Setting up Postgresql Database
  default: &default
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: localhost
    port: 5432

  development:
    <<: *default
    database: todoapi_development
    username: luminos
    password: luminos

  test:
    <<: *default
    database: apitodo_development
    username: luminos
    password: luminos
